### ISSUE TITLE
Add links to extensions picture

### ISSUE THREAD

**Issue by bpaniagua** [slicercmf/slicercmf.github.io#1]
In landing page, figure should include links to extensions Slicer wiki documentation pages such as i.e.
https://www.slicer.org/wiki/Documentation/4.6/Extensions/PickAndPaint

**Comment by ClementMirabel** [comment]
Done by commits 1388ab1924d97b6a4fed7e01dd48d7cd5414defd and 09bacd779b3d80b28e148c91abfde941d7247d06.
